[phases.setup]
nixPkgs = ["php82", "php82Extensions.composer", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.curl", "php82Extensions.dom", "php82Extensions.fileinfo", "libmysqlclient", "nodejs"]

[variables]
NIXPACKS_PHP_VERSION = "8.2"
